services:
  database:
    image: postgres:16.4-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_board
